export const EXTRA_PAGES = [
  ['/help/account', 'Account help'],
  ['/help/safety', 'Safety'],
  ['/help/creators', 'Creator help'],
  ['/help/payments', 'Payments help'],
  ['/legal/copyright', 'Copyright Policy'],
  ['/legal/verification', 'Verification Policy'],
  ['/legal/spam', 'Spam Policy'],
  ['/legal/manipulation', 'Platform Manipulation Policy'],
  ['/legal/payments', 'Payment Terms'],
  ['/legal/creator', 'Creator Policy'],
  ['/legal/api', 'API Terms'],
  ['/studio/calendar', 'Content calendar'],
  ['/studio/schedule', 'Scheduled publishing'],
  ['/studio/thumbs', 'Thumbnail management'],
  ['/studio/playlists', 'Playlists'],
  ['/studio/comments', 'Comment moderation'],
  ['/studio/mods', 'Moderator management'],
  ['/studio/audience', 'Audience analytics'],
  ['/studio/compare', 'Performance comparison'],
  ['/studio/keywords', 'Search keywords'],
  ['/studio/hashtags', 'Hashtag performance'],
  ['/studio/growth', 'Follower growth'],
  ['/studio/watchtime', 'Watch-time analytics'],
  ['/studio/retention', 'Retention graph'],
  ['/studio/traffic', 'Traffic sources'],
  ['/studio/recs', 'Content recommendations'],
  ['/studio/copyright', 'Copyright status'],
  ['/studio/guidelines', 'Community guideline status'],
  ['/studio/brand', 'Branding'],
  ['/studio/notify', 'Notification analytics'],
  ['/settings/account', 'Account'],
  ['/settings/language', 'Language'],
  ['/settings/accessibility', 'Accessibility'],
  ['/settings/notifications', 'Notification preferences'],
  ['/settings/data', 'Download my data'],
  ['/explore/trending', 'Trending'],
  ['/explore/topics', 'Topics'],
  ['/explore/videos', 'Explore videos'],
  ['/notifications/mentions', 'Mentions'],
  ['/notifications/system', 'System alerts'],
]
